### ISSUE TITLE
Serve overview on public IP (instead of localhost:9000)

### ISSUE THREAD

**Issue by tpmccallum** [overview/overview-server#627]
Hi,
Is there config to serve Overview on a public facing server rather than localhost?
I want to collaborate on public documents in an Overview environment with other colleagues.
Thanks
Tim

**Comment by jstray** [comment]
Yes, you can turn the multi-user flag on to get the same as
overviewproject.org. But we don't really support more than one person at a
time editing, yet.

**Comment by adamhooper** [comment]
You probably want to use either iptables or a reverse proxy such as haproxy or nginx. We don't document the general procedure, because that's a bit out of scope for us. There are oodles of tutorials online; after a brief search I found https://www.digitalocean.com/community/tutorials/how-to-use-haproxy-as-a-layer-7-load-balancer-for-wordpress-and-nginx-on-ubuntu-14-04, which seems to do a good job of describing what's up.

While we don't document reverse proxies in general, we *do* document a couple of subtleties that affect Overview: https://github.com/overview/overview-server/wiki/Configuring-a-reverse-proxy-server
